### PR TITLE
chore: Add plugin verification to pre-merge action.

### LINKED ISSUE #116: Add plugin verification to pre-merge action.
It would be nice if the [Intellij Platform Plugin Verification](https://github.com/marketplace/actions/intellij-platform-plugin-verifier) action would added the the pre-merge step. That way issues can be known before submitting the plugin.

### PR DESCRIPTION
**Pull request by Unthrottled**
# Motivation

Fixes #116

### CODE REVIEW

**Comment by zd-zero** [comment]
I think that we should create another file for these changes? Can we move this to `compatibility.yml`? This helps to separate their responsibilities. Or rename the `gradle.yml` to `workflows.yml` instead? But this may lead to multiple workflows in one file.

**Comment by Unthrottled** [comment]
The compatibility action requires the plugin to be built, so it feels kind of redundant (and more time to wait) to have to build the plugin twice just to get all the checks complete. So I'll opt to rename it `pre-merge.yml` because it should only really need to run there. Thoughts? :thinking:

**Comment by zd-zero** [comment]
Alright, we'll just rename it to `pre-merge.yml` 👍

**Comment by Unthrottled** [comment]
Re-Named!

> So we don't need to wait longer for our Waifu

#priorities

**Pull request merged**
