### PR TITLE
chore: bump ktlint to 9.4.1

### PR DESCRIPTION
**Pull request by zd-zero**
This PR bump the ktlint to `9.4.1` and performed the `ktlintFormat` and turns out that it hates star imports so added a project Kotlin code style to prevent the usage of star imports.

### CODE REVIEW

**Review by Unthrottled — APPROVED** [review]
> When I realize I can use Kotlin 1.4.10 features but have to fix merge conflicts now

MFW

**Comment by Unthrottled** [comment]
I change the commit message from `core: bump ktlint to 9.4.1` to `chore: bump ktlint to 9.4.1` (assuming you wanted chore as the commit message)

**Comment by zd-zero** [comment]
> When I realize I can use Kotlin 1.4.10 features but have to fix merge conflicts now

Wait, I don't get this 😵, I can't find the source of the quote. If there's a merge conflict to another story, we should merge that first then rebase from there.

**Comment by Unthrottled** [comment]
I'm still working on #235 right now, it's not that big of a deal.

**Comment by zd-zero** [comment]
Hmmm, I think it would be better to merge that first as the linter can do its job later (can add this to a poem). What do you think?

**Comment by Unthrottled** [comment]
That works for me.

I've got a couple 1.4.10 features that I want to convert to, do you think that should be a separate pr?

**Comment by zd-zero** [comment]
> I've got a couple 1.4.10 features that I want to convert to, do you think that should be a separate pr?

If you think that the story is related to it, then go for it, but in case of the module is non-relevant, then I'd suggest to separate it to a different PR, the reasoning behind is if ever we want to revert commits, we can still retain the wanted changes only revert the relevant ones.

**Comment by Unthrottled** [comment]
It should probably be a separate task, that depends on this.

**Pull request merged**
